# Generated by Django 2.2.4 on 2020-01-15 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user', models.ManyToManyField(related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('current_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_block_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
