# Generated by Django 2.2.4 on 2020-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191222_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='reaction',
            field=models.CharField(choices=[('Liked', 'Liked'), ('Commented', 'Commented'), ('Mentioned', 'Mentioned'), ('Sent Follow Request', 'Sent Follow Request'), ('Accept Follow Request', 'Accept Follow Request'), ('Replied', 'Replied')], max_length=50),
        ),
    ]
